package com.foxtrader.app.domain.model

/**
 * Provenance of a cached candle series.
 *
 * FoxTrader seeds synthetic bars whenever a provider is unreachable so the
 * chart is never blank. That behaviour is only safe if synthetic bars are
 * *distinguishable* from real ones: the AI, the scanner and the backtester all
 * produce confident directional narratives, and a trader must never mistake a
 * narrative computed over a random walk for one computed over their broker's
 * prices.
 *
 * Provenance is deliberately modelled at the **series** level rather than on
 * [Candle]. A candle is the atomic unit of price maths shared by every
 * indicator; adding a non-numeric field to it would pollute ~50 construction
 * sites and every pure function that rebuilds bars. Where a bar came from is
 * metadata *about a fetch*, not a property of the price itself.
 *
 * Ordering matters: [worstOf] uses the declaration order to collapse a mixed
 * series down to its least trustworthy member.
 */
enum class CandleSource {
    /** Fetched from a real provider in this session. */
    LIVE,

    /** Read from the local Room cache; was real when it was written. */
    CACHED,

    /** Generated by [com.foxtrader.app.data.repository.SampleData]. Not real. */
    SYNTHETIC,
    ;

    /** True when this data must not be used to authorise a trade decision. */
    val isTrustworthy: Boolean get() = this != SYNTHETIC

    companion object {
        /**
         * The least trustworthy source in [sources], i.e. the one that should
         * govern how a mixed series is labelled and gated.
         *
         * An empty series is [SYNTHETIC]-free but also evidence-free; it is
         * reported as [CACHED] so that "no data" never masquerades as live.
         */
        fun worstOf(sources: Iterable<CandleSource>): CandleSource =
            sources.maxByOrNull { it.ordinal } ?: CACHED

        /** Parses a persisted column value, defaulting to [LIVE] for legacy rows. */
        fun fromStorage(raw: String?): CandleSource =
            entries.firstOrNull { it.name == raw } ?: LIVE
    }
}

/**
 * A candle series plus where it came from.
 *
 * Returned by the repository so callers can gate on provenance without having
 * to inspect individual bars.
 */
data class SourcedCandles(
    val candles: List<Candle>,
    val source: CandleSource,
) {
    val isSynthetic: Boolean get() = source == CandleSource.SYNTHETIC
    val isEmpty: Boolean get() = candles.isEmpty()

    companion object {
        val EMPTY = SourcedCandles(emptyList(), CandleSource.CACHED)
    }
}
