package com.foxtrader.app.domain.model.tradepro

import com.foxtrader.app.domain.model.Direction

// ---------------------------------------------------------------------------
// Portfolio-level risk domain models for the TRADEPRO risk manager.
// All risk is expressed in *points* (instrument-agnostic). Dollar conversion is
// deferred to the presentation layer.
// ---------------------------------------------------------------------------

/**
 * Heat contribution of a single open position to the overall portfolio risk budget.
 *
 * @property symbol Instrument ticker.
 * @property direction Trade direction.
 * @property riskPoints Points at risk for this position (distance to stop * contracts).
 * @property heatPercent Fraction (0..1) of the total risk budget consumed by this position.
 */
data class PositionHeat(
    val symbol: String,
    val direction: Direction,
    val riskPoints: Double,
    val heatPercent: Double,
)

/**
 * Aggregate risk snapshot of the entire portfolio at a point in time.
 *
 * @property currentEquity Account equity in points (running total).
 * @property dailyPnl Net points gained/lost today.
 * @property openRisk Sum of risk-points across all open positions.
 * @property maxRiskBudget Maximum total risk-points allowed at any moment.
 * @property correlationExposure Fraction (0..1) of risk concentrated in correlated instruments.
 * @property positionHeat Per-position heat breakdown.
 * @property riskUtilizationPercent Percentage (0..100) of risk budget currently in use.
 * @property consecutiveLosses Number of back-to-back losses in the current session.
 * @property tradesTakenToday Number of trades executed in the current session.
 */
data class PortfolioRiskState(
    val currentEquity: Double = 0.0,
    val dailyPnl: Double = 0.0,
    val openRisk: Double = 0.0,
    val maxRiskBudget: Double = 30.0,
    val correlationExposure: Double = 0.0,
    val positionHeat: List<PositionHeat> = emptyList(),
    val riskUtilizationPercent: Double = 0.0,
    val consecutiveLosses: Int = 0,
    val tradesTakenToday: Int = 0,
)

/**
 * Result of the Kelly-criterion position sizing engine.
 *
 * @property recommendedContracts Contracts to deploy (always >= 1 when a trade is allowed).
 * @property riskPerContract Risk in points per single contract.
 * @property totalRiskPoints Total risk committed (recommendedContracts * riskPerContract).
 * @property kellyFraction Raw Kelly fraction before half-Kelly safety discount.
 * @property maxDrawdownBudget Remaining points available before the daily hard-stop.
 */
data class PositionSizeResult(
    val recommendedContracts: Int,
    val riskPerContract: Double,
    val totalRiskPoints: Double,
    val kellyFraction: Double,
    val maxDrawdownBudget: Double,
)

/**
 * Rolling daily performance record. Updated after every closed trade.
 *
 * @property date Calendar date (ISO-8601 string, e.g. "2024-06-15").
 * @property tradesTaken Total trades taken so far today.
 * @property wins Number of winning trades.
 * @property losses Number of losing trades.
 * @property netPoints Cumulative net P/L in points.
 * @property cumulativeEquity Running equity in points.
 * @property peakEquity High-water mark for drawdown calculation.
 * @property drawdown Current drawdown from peak (positive value, in points).
 * @property complianceScore Plan-adherence score (0..100).
 */
data class DailyPerformance(
    val date: String = "",
    val tradesTaken: Int = 0,
    val wins: Int = 0,
    val losses: Int = 0,
    val netPoints: Double = 0.0,
    val cumulativeEquity: Double = 0.0,
    val peakEquity: Double = 0.0,
    val drawdown: Double = 0.0,
    val complianceScore: Double = 100.0,
)

// ---------------------------------------------------------------------------
// Risk alert system
// ---------------------------------------------------------------------------

/** Severity tiers for portfolio risk alerts. */
enum class AlertSeverity {
    /** Informational — no action required. */
    INFO,
    /** Warning — consider reducing exposure or pausing. */
    WARNING,
    /** Critical — immediate action required (stand aside). */
    CRITICAL,
}

/** Categories of risk alerts generated by the portfolio risk engine. */
enum class RiskAlertType {
    /** Approaching or past the daily loss cap. */
    DAILY_LIMIT,
    /** Excessive correlation concentration across open positions. */
    CORRELATION,
    /** Drawdown from equity peak exceeds threshold. */
    DRAWDOWN,
    /** Consecutive loss streak beyond acceptable limit. */
    STREAK,
    /** Emotional tilt indicator (e.g. abnormally high trade frequency). */
    TILT,
}

/**
 * A discrete risk alert emitted by the engine.
 *
 * @property type Classification of the risk condition.
 * @property severity How urgently the trader must act.
 * @property message Human-readable description of the alert.
 * @property value Numeric metric triggering the alert (e.g. loss amount, streak count).
 * @property threshold Threshold that was breached.
 */
data class RiskAlert(
    val type: RiskAlertType,
    val severity: AlertSeverity,
    val message: String,
    val value: Double = 0.0,
    val threshold: Double = 0.0,
)

// ---------------------------------------------------------------------------
// Correlation model
// ---------------------------------------------------------------------------

/**
 * A group of instruments that share meaningful statistical correlation.
 *
 * @property symbols Instruments in this correlation cluster.
 * @property correlationCoefficient Average pairwise correlation (0..1).
 * @property combinedExposure Total risk-points deployed across the group.
 */
data class CorrelationGroup(
    val symbols: List<String>,
    val correlationCoefficient: Double,
    val combinedExposure: Double,
)

// ---------------------------------------------------------------------------
// Trade gate decision
// ---------------------------------------------------------------------------

/**
 * Final decision from the portfolio risk engine on whether a new trade should proceed.
 * Each variant carries a human-readable [reason].
 */
sealed class RiskDecision(open val reason: String) {
    /** All risk checks pass; the trade may proceed at full size. */
    data class Proceed(override val reason: String = "All risk checks passed.") : RiskDecision(reason)

    /** Risk is elevated; proceed at reduced position size. */
    data class ReduceSize(override val reason: String) : RiskDecision(reason)

    /** Risk is unacceptable; stand aside entirely. */
    data class StandAside(override val reason: String) : RiskDecision(reason)
}
