package com.foxtrader.app.data.remote.api

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import okhttp3.HttpUrl.Companion.toHttpUrl
import retrofit2.http.Body
import retrofit2.http.GET
import retrofit2.http.Header
import retrofit2.http.POST
import retrofit2.http.Path
import retrofit2.http.Query
import retrofit2.http.Url

/**
 * Retrofit contract for MetaApi.
 *
 * IMPORTANT: MetaApi uses different hosts for provisioning, terminal REST/RPC,
 * and historical market data. The Retrofit base URL is the provisioning host;
 * terminal/market-data calls therefore use an absolute [Url] generated by
 * [MetaApiEndpointResolver] after resolving the provisioned account region.
 */
interface MetaApiService {

    @POST("/users/current/accounts")
    suspend fun deployAccount(
        @Header("auth-token") authToken: String,
        @Header("transaction-id") transactionId: String,
        @Body request: MetaApiDeployRequest,
    ): MetaApiDeployResponse

    /** Reads provisioning metadata (including the deployment region). */
    @GET("/users/current/accounts/{accountId}")
    suspend fun getProvisionedAccount(
        @Header("auth-token") authToken: String,
        @Path("accountId") accountId: String,
    ): MetaApiProvisionedAccountResponse

    /** Idempotently starts the API server/terminal for an existing account. */
    @POST("/users/current/accounts/{accountId}/deploy")
    suspend fun deployProvisionedAccount(
        @Header("auth-token") authToken: String,
        @Path("accountId") accountId: String,
        @Query("executeForAllReplicas") executeForAllReplicas: Boolean = true,
    )

    @GET
    suspend fun getAccountInformation(
        @Url url: String,
        @Header("auth-token") authToken: String,
        @Query("refreshTerminalState") refreshTerminalState: Boolean = false,
    ): MetaApiAccountInfoResponse

    @GET
    suspend fun getPositions(
        @Url url: String,
        @Header("auth-token") authToken: String,
        @Query("refreshTerminalState") refreshTerminalState: Boolean = false,
    ): List<MetaApiPositionResponse>

    @GET
    suspend fun getOrders(
        @Url url: String,
        @Header("auth-token") authToken: String,
        @Query("refreshTerminalState") refreshTerminalState: Boolean = false,
    ): List<MetaApiOrderResponse>

    @POST
    suspend fun executeTrade(
        @Url url: String,
        @Header("auth-token") authToken: String,
        @Body request: MetaApiTradeRequest,
    ): MetaApiTradeResponse

    /** Current broker price; used by the Android-safe polling quote stream. */
    @GET
    suspend fun getCurrentPrice(
        @Url url: String,
        @Header("auth-token") authToken: String,
        @Query("keepSubscription") keepSubscription: Boolean = true,
    ): MetaApiCurrentPriceResponse

    /**
     * Historical-market-data API returns a JSON array, not a wrapper object.
     * `startTime` is ISO-8601 when supplied.
     */
    @GET
    suspend fun getHistoricalCandles(
        @Url url: String,
        @Header("auth-token") authToken: String,
        @Query("startTime") startTime: String? = null,
        @Query("limit") limit: Int? = null,
    ): List<MetaApiCandleResponse>

    @GET
    suspend fun getSymbolSpecification(
        @Url url: String,
        @Header("auth-token") authToken: String,
    ): MetaApiSymbolSpecResponse

    /** History deals for one position; used to recover authoritative realized P/L. */
    @GET
    suspend fun getDealsByPosition(
        @Url url: String,
        @Header("auth-token") authToken: String,
    ): List<MetaApiDealResponse>
}

/**
 * Resolves MetaApi regional REST hosts without accepting arbitrary origins.
 * Provisioning metadata can use multiple geographic regions, so region labels
 * are validated as a single DNS label and interpolated only beneath the fixed
 * `agiliumtrade.ai` API suffix. Legacy `vint-hill` is mapped to `new-york`.
 */
object MetaApiEndpointResolver {
    private const val CLIENT_PREFIX = "https://mt-client-api-v1."
    private const val MARKET_PREFIX = "https://mt-market-data-client-api-v1."
    private const val SUFFIX = ".agiliumtrade.ai"

    fun normalizeRegion(region: String): String {
        val normalized = region.trim().lowercase().let { if (it == "vint-hill") "new-york" else it }
        require(normalized.length in 2..40 && REGION_LABEL.matches(normalized)) {
            "Invalid MetaApi deployment region '$region'"
        }
        return normalized
    }

    /**
     * Builds a client REST URL with each dynamic component encoded as one path
     * segment. Broker symbols can legitimately contain characters such as `/`,
     * `#` or spaces; concatenating them into a URL is both incorrect and unsafe.
     */
    /** Socket.IO origin for the regional MetaApi client API. */
    fun clientOrigin(region: String): String {
        val r = normalizeRegion(region)
        return "$CLIENT_PREFIX$r$SUFFIX"
    }

    fun clientUrl(region: String, accountId: String, vararg pathSegments: String): String {
        val r = normalizeRegion(region)
        val builder = "$CLIENT_PREFIX$r$SUFFIX".toHttpUrl().newBuilder()
            .addPathSegment("users")
            .addPathSegment("current")
            .addPathSegment("accounts")
            .addPathSegment(requirePathValue(accountId, "account id"))
        pathSegments.forEach { builder.addPathSegment(requirePathValue(it, "path segment")) }
        return builder.build().toString()
    }

    fun marketDataCandlesUrl(region: String, accountId: String, symbol: String, timeframe: String): String {
        val r = normalizeRegion(region)
        return "$MARKET_PREFIX$r$SUFFIX".toHttpUrl().newBuilder()
            .addPathSegment("users")
            .addPathSegment("current")
            .addPathSegment("accounts")
            .addPathSegment(requirePathValue(accountId, "account id"))
            .addPathSegment("historical-market-data")
            .addPathSegment("symbols")
            .addPathSegment(requirePathValue(symbol, "symbol"))
            .addPathSegment("timeframes")
            .addPathSegment(requirePathValue(timeframe, "timeframe"))
            .addPathSegment("candles")
            .build()
            .toString()
    }

    private val REGION_LABEL = Regex("^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$")

    private fun requirePathValue(value: String, label: String): String {
        val v = value.trim()
        require(v.isNotEmpty() && v.length <= 128) { "Invalid MetaApi $label" }
        require(v.none { it.isISOControl() }) { "Invalid MetaApi $label" }
        return v
    }
}

// ============================================================================
// REQUEST DTOs
// ============================================================================

@Serializable
data class MetaApiDeployRequest(
    /** MetaApi provisioning API documents login as a digit string. */
    val login: String,
    val password: String,
    val name: String,
    val server: String,
    val platform: String = "mt4",
    val type: String = "cloud-g2",
    val magic: Int = 0,
    val manualTrades: Boolean = true,
)

@Serializable
data class MetaApiTradeRequest(
    val actionType: String,
    val symbol: String? = null,
    val volume: Double? = null,
    val openPrice: Double? = null,
    @SerialName("stopLoss") val stopLoss: Double? = null,
    @SerialName("takeProfit") val takeProfit: Double? = null,
    val positionId: String? = null,
    val orderId: String? = null,
    val trailingStopLoss: MetaApiTrailingStopLoss? = null,
    val expiration: MetaApiOrderExpiration? = null,
    val clientId: String? = null,
    val comment: String = "FoxTrader",
)

@Serializable
data class MetaApiOrderExpiration(
    val type: String,
    val time: String? = null,
)

@Serializable
data class MetaApiTrailingStopLoss(
    val distance: MetaApiTrailingDistance? = null,
)

@Serializable
data class MetaApiTrailingDistance(
    val distance: Double,
    val units: String = "RELATIVE_POINTS",
)

// ============================================================================
// RESPONSE DTOs
// ============================================================================

@Serializable
data class MetaApiDeployResponse(
    val id: String = "",
    val state: String = "",
)

@Serializable
data class MetaApiProvisionedAccountResponse(
    @SerialName("_id") val id: String = "",
    val login: String = "",
    val name: String = "",
    val server: String = "",
    val platform: String = "",
    val state: String = "",
    val connectionStatus: String = "",
    val region: String = "",
)

@Serializable
data class MetaApiAccountInfoResponse(
    val login: Long = 0L,
    val balance: Double = 0.0,
    val equity: Double = 0.0,
    val margin: Double = 0.0,
    val freeMargin: Double = 0.0,
    val leverage: Int = 0,
    val currency: String = "USD",
    val name: String = "",
    val server: String = "",
)

@Serializable
data class MetaApiPositionResponse(
    val id: String = "",
    val symbol: String = "",
    val type: String = "",
    val volume: Double = 0.0,
    val openPrice: Double = 0.0,
    /** ISO-8601 on the current MetaApi REST API. */
    val time: String = "",
    @SerialName("stopLoss") val stopLoss: Double = 0.0,
    @SerialName("takeProfit") val takeProfit: Double = 0.0,
    val profit: Double = 0.0,
    val swap: Double = 0.0,
    val commission: Double = 0.0,
)

@Serializable
data class MetaApiOrderResponse(
    val id: String = "",
    val type: String = "",
    val state: String = "",
    val symbol: String = "",
    val time: String = "",
    val openPrice: Double = 0.0,
    val currentPrice: Double = 0.0,
    @SerialName("stopLoss") val stopLoss: Double = 0.0,
    @SerialName("takeProfit") val takeProfit: Double = 0.0,
    val volume: Double = 0.0,
    val currentVolume: Double = 0.0,
    val expirationType: String = "ORDER_TIME_GTC",
    val expirationTime: String? = null,
)

@Serializable
data class MetaApiTradeResponse(
    val numericCode: Int = 0,
    val stringCode: String = "",
    /** MetaApi examples encode ids as strings. */
    val orderId: String = "",
    val positionId: String = "",
    val message: String = "",
)

@Serializable
data class MetaApiCurrentPriceResponse(
    val symbol: String = "",
    val bid: Double = 0.0,
    val ask: Double = 0.0,
    val time: String = "",
    val brokerTime: String = "",
)

@Serializable
data class MetaApiCandleResponse(
    val symbol: String = "",
    val timeframe: String = "",
    /** ISO-8601 on the current historical market-data API. */
    val time: String = "",
    val open: Double = 0.0,
    val high: Double = 0.0,
    val low: Double = 0.0,
    val close: Double = 0.0,
    @SerialName("tickVolume") val tickVolume: Double = 0.0,
    val volume: Double = 0.0,
)

@Serializable
data class MetaApiSymbolSpecResponse(
    val symbol: String = "",
    @SerialName("tickSize") val tickSize: Double = 0.0,
    @SerialName("minVolume") val minVolume: Double = 0.0,
    @SerialName("maxVolume") val maxVolume: Double = 0.0,
    @SerialName("volumeStep") val volumeStep: Double = 0.0,
    @SerialName("contractSize") val contractSize: Double = 0.0,
    /** Broker-reported point size; distinct from tickSize on some instruments. */
    val point: Double = 0.0,
    /** Base currency from MetaApi symbol specification (e.g. EUR for EURUSD). */
    val baseCurrency: String = "",
    /** Profit/quote currency from MetaApi (e.g. USD for EURUSD). */
    val profitCurrency: String = "",
    val digits: Int = 5,
    val description: String = "",
    /** Minimum distance from current price to SL/TP/pending open price, in points. */
    val stopsLevel: Double = 0.0,
    /** Pending-order modification freeze distance, in points. */
    val freezeLevel: Double = 0.0,
    val allowedOrderTypes: List<String> = emptyList(),
    val allowedExpirationModes: List<String> = emptyList(),
)

@Serializable
data class MetaApiDealResponse(
    val id: String = "",
    val type: String = "",
    @SerialName("entryType") val entryType: String = "",
    val symbol: String = "",
    val time: String = "",
    val volume: Double = 0.0,
    val price: Double = 0.0,
    val commission: Double = 0.0,
    val swap: Double = 0.0,
    val profit: Double = 0.0,
    @SerialName("positionId") val positionId: String = "",
    @SerialName("orderId") val orderId: String = "",
    val platform: String = "",
)

